services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: host
    env_file: ./.env
    volumes:
      - ./config:/config
      - ./media:/media
    restart: unless-stopped